Distance
MorganLee909/market pull request #11
Opened 2021-04-29 14:50 UTC by ivanko22

2021-04-29 17:54 UTC, MorganLee909 commented on app.js
> +    minimize: true
Leave this false. We only want to minimize in production.

2021-04-30 09:06 UTC, MorganLee909 commented on views/js/models/Vendor.js
> +        this._distance = `${(distance * 0.001).toFixed(1)} mi`;
Why did you change this to kilometers? I told you to assume that it was miles and that I would fix it.

2021-04-30 09:15 UTC, MorganLee909 requested changes
You need to store the number on the class, not a string that you want displayed. Classes are for storing the data.

Also, the branch is named 'distance' but you made changes to the css in the components. I'll accept it this time, but in the future, I will refuse PR's that do multiple different things.

2021-04-30 09:44 UTC, ivanko22 commented on app.js
> +    minimize: true
done

2021-04-30 10:02 UTC, ivanko22 commented
updated

2021-04-30 10:03 UTC, MorganLee909 commented on views/js/pages/searchResults.js
> +            item.setAttribute('distance', `${(vendors[i].distance * 0.001).toFixed(1)} mi` );
You are still converting to km for some reason.  Remember, I said to assume that distance is being returned in miles? I will update the backend before merging to send miles. Just don't multiply the distance by anything.

2021-04-30 10:10 UTC, MorganLee909 commented
You are still converting to km for some reason. Just display the distance, don't multiply it by anything.

2021-04-30 10:53 UTC, MorganLee909 approved these changes

2021-04-30 10:53 UTC, merged